name: galli_map
description: A Galli map widget that displays a map with custom markers, lines, circles and polygons. 
version: 0.0.9
homepage: https://www.gallimaps.com

environment:
  sdk: '>=2.12.0<3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  flutter_svg: ^0.23.0
  flutter_map: ^0.13.1
  latlong2: ^0.8.1
  geolocator: ^7.7.0
  flutter_compass: ^0.7.0



dev_dependencies:

flutter:
